title: read-the-docs-jekyll-theme
description: Read the Docs like Jekyll Theme for GitHub Pages

theme: null

debug:
  compress: true
  dist: false
  shortcodes: true

url: http://127.0.0.1:4000

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - node_modules
  - package-lock.json
  - package.json
  - Pipfile
  - Pipfile.lock
  - read-the-docs-jekyll-theme.gemspec
  - requirements.txt
  - webpack.config.js
