title: read-the-docs-jekyll-theme
description: Read the Docs like Jekyll Theme for GitHub Pages

theme: null

google:
  gtag: G-SRXFW33ENB
  site_verification: ChPjQbKFflPAwOF9uuYRLEodZBgPjW5CISg0gSsViN0

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - node_modules
  - package-lock.json
  - package.json
  - Pipfile
  - Pipfile.lock
  - read-the-docs-jekyll-theme.gemspec
  - requirements.txt
  - webpack.config.js
